# Generated by Django 2.2 on 2021-07-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='is_responded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='is_responded',
            field=models.BooleanField(default=False),
        ),
    ]
