# Generated by Django 2.2 on 2021-07-08 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210707_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='benchpress',
            field=models.IntegerField(null=True, verbose_name='benchpress'),
        ),
    ]
